'use strict';
class OpenEducationTagger {
  constructor() {

    // 2DO: case convention

    // submitted from outside
    this.oet_spreadsheet_sheet_id;
    this.oet_spreadsheet_sheet_id;
    this.oet_elasticsearch_hostname;
    this.oet_elasticsearch_index;
    this.oet_elasticsearch_auth_string_write;

    // generated by this class
    this.spreadsheetJsonUrl;
  }
  setConfig(configObject) {
    console.log('oet - setConfig', configObject);
    // 2DO: use isset | shortcut
    this.oet_spreadsheet_id = configObject.oet_spreadsheet_id;
    this.oet_spreadsheet_sheet_id = configObject.oet_spreadsheet_sheet_id;
    this.oet_elasticsearch_hostname = configObject.oet_elasticsearch_hostname;
    this.oet_elasticsearch_index = configObject.oet_elasticsearch_index;
    this.oet_elasticsearch_auth_string_write = configObject.oet_elasticsearch_auth_string_write;

    this.spreadsheetJsonUrl = 'https://spreadsheets.google.com/feeds/list/' + this.oet_spreadsheet_id + '/' + this.oet_spreadsheet_sheet_id + '/public/values?alt=json';
    console.log('set spreadsheet url', this.spreadsheetJsonUrl);

    // 2DO: validate all values, show error?

    console.log('updated config, values are now:',this);
  }
  syncSpreadsheetToIndex() {
    // https://spreadsheets.google.com/feeds/list/1kntJWO9iP6rL6WFqKXNsINoa923LjoDfEz38_NA4-ao/od6/public/values?alt=json

    // https://www.electronjs.org/docs/api/client-request
    /*const stream = require('stream')
    const {net} = require('electron').remote

    const request = net.request({
      method: 'GET',
      protocol: 'https:',
      hostname: 'spreadsheets.google.com',
      port: 443,
      path: '/feeds/list/1kntJWO9iP6rL6WFqKXNsINoa923LjoDfEz38_NA4-ao/od6/public/values?alt=json'
    });

    request.on('response', (response) => {
      console.log(`STATUS electron request: ${response.statusCode}`);
      response.on('error', (error) => {
        console.log(`ERROR: ${JSON.stringify(error)}`)
      })
    })
    request.on('login', (authInfo, callback) => {
      callback()
    })*/

    // 2DO: good style to do it here this way?
    // this needs to be made available in preload.js
    const https = window.https;
    const tryjson = window.tryjson;

    // our class



  /*  async.waterfall([
      function(done) {
        done(null, 'Value 1');
      },
      function(value1, done) {
        console.log(value1);
        done(null, 'Value 2');
      },
      function(value2, done) {
        console.log(value2);
        done(null, 'done');
      }
    ], function(err) {
      if (err) throw new Error(err);
    });*/



    var options = {
      host: 'spreadsheets.google.com',
      path: '/feeds/list/1kntJWO9iP6rL6WFqKXNsINoa923LjoDfEz38_NA4-ao/od6/public/values?alt=json',
      headers: {
        'User-Agent': 'request'
      }
    };

    // save reference to class for callback
    // better way - async waterfall?
    // https://blog.cloudboost.io/execute-asynchronous-tasks-in-series-942b74697f9c
    // https://www.codementor.io/@aminmeyghani/running-asynchronous-javascript-code-in-sequence-with-async-waterfall---part-1-du1084fmx

    const theCurrentClassInstance = this;

    https.get(options, function(res) {
      var json = '';

      res.on('data', function(chunk) {
        //console.log('data',chunk);
        json += chunk;
      });

      res.on('end', function() {
        if (res.statusCode === 200) {
          console.log('Status:', res.statusCode);
          console.log('res', res);
          console.log('THIS:', this);
          console.log('theCurrentClassInstance', theCurrentClassInstance);
          var data = tryjson.parse(json);
          console.log(data ? data : 'Error parsing JSON!');

          // tryjson will return undefined on parsing error
          if (data !== undefined) {
            theCurrentClassInstance.convertAndSubmitJsonToIndex(data);
          }
        } else {
          console.log('Status:', res.statusCode);
        }
      });
    }).on('error', function(err) {
      console.log('Error:', err);
    }); // eo https get

  }
  convertAndSubmitJsonToIndex(spreadsheetJson) {
    console.log('convertAndsubmitJsonToIndex called');
    console.log('convertAndsubmitJsonToIndex this', this);
    // 2DO: check if feed.entry is set
    // important: set ,thisValue
    spreadsheetJson.feed.entry.forEach(function(item, index) {
      // 2DO: add debug option to just parse 1 item?
      if (index == 0) {

        console.log('converting item', item, index);

        let sanitizedObject = {};

        // 2DO: use config values for that later
        // 2DO: convert URL

        // access via bracket notation
        // example for json:
        /* "gsx$titel":{
                "$t":"Test-Titel"
             },*/
        sanitizedObject.title = item['gsx$titel']['$t'];
        console.log('sanitized object', sanitizedObject);

        this.sendObjectToIndex(sanitizedObject);

      } // 2DO: remove, only for testing

    }, this); // !important -> this binding!
  }
  sendObjectToIndex(objectToSend) {

    console.log('sendObjectToIndex', objectToSend);

    // 2DO: good style to do it here this way?
    const https = window.https;
    // safer parsing
    const tryjson = window.tryjson;

    // configure authentication
    // 2DO: use stored values
    // let userAndPass = 'SxXGi7v3m:cc24f410-91dc-4bd5-8b84-1b19fe0dc567';
    const userAndPass = this.oet_elasticsearch_auth_string_write;
    const authString = "Basic " + btoa(userAndPass); // base64 encoding
    console.log('authString', authString);

    // 2DO: index or update (Get it first by URL, see PHP code)

    const data = JSON.stringify(objectToSend);
    // see at bottom, will be send via req.write(data)

    const options = {
      host: 'scalr.api.appbase.io',
      path: '/openeducationtagger-playground/_doc', // 2DO: index or update
      method: 'POST',
      headers: {
        // 'User-Agent': 'request',
        'Authorization': authString,
        "Content-Type": "application/json",
        'Content-Length': data.length
      }
    };

    // post it
    const req = https.request(options, function(res) {
      var jsonResponse = '';

      console.log('send POST to index', res);

      res.on('data', function(chunk) {
        //console.log('data',chunk);
        jsonResponse += chunk;
      });

      res.on('end', function() {
        // 201 = created
        if (res.statusCode === 200 || res.statusCode === 201) {
          console.log('Status:', res.statusCode);
          console.log('res', res);
          var data = tryjson.parse(jsonResponse);
          console.log('data parsed', data ? data : 'Error parsing JSON!');

          // tryjson will return undefined on parsing error
          if (data !== undefined) {
            // new id will be _id: "kX9qDHEBtWjoDWKpNl2U",
            console.log('got data successful', data);
          }
        } else {
          console.log('Status:', res.statusCode);
        }
      });
    }).on('error', function(err) {
      console.log('Error:', err);
    }); // eo https get

    // 2DO: is this needed?
    req.on('error', (e) => {
      console.error(e);
    });

    req.write(data)
    req.end();

  }
  set name(name) {
    this._name = name.charAt(0).toUpperCase() + name.slice(1);
  }
  get name() {
    return this._name;
  }
  sayHello() {
    console.log('Hello, my name is ' + this.name + ', I have ID: ' + this.id);
  }
}
